### ISSUE TITLE
[BUG] daemon cannot run if /a is not exists in system

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#116]
**Describe the bug**

The current daemon exists a hack:

```c
	// strncpy(obj->rodata->new_uprobe_path, env.new_uprobe_path, PATH_LENTH);
	// TODO: currently using `/a` as the replacing executable path to uprobe
	// perf event in the kernel, since long strings (such as bpftime_daemon it self)
	// may break userspace memory.
	// Find a better way to solve this in the future
	strncpy(obj->rodata->new_uprobe_path, "/a", PATH_LENTH);
```

This will make the uprobe failed if /a is not exist as an elf.

**To Reproduce**

run daemon

**Expected behavior**

1. can we found a better way to solve this?
2. Maybe we can create the /a file in advance?

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. Windows]
* Version [e.g. 10]

**Additional context**

**Comment by Officeyutong** [comment]
Workaround: create /a when running daemon
