### ISSUE TITLE
[FEATURE] Add remote attach and detach support

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#156]
**Is your feature request related to a problem? Please describe.**

After the bpftime-agent.so dyn lib is loaded, the remote libbpf should be able to control to detach of uprobe. Currently we have it support in bpftime-agent.so, but not syscall server.

**Describe the solution you'd like**

We need a mechanism to pass message and better control the states of eBPF runtime.

**Describe alternatives you've considered**

**Provide usage examples**

**Additional context**

**Comment by Officeyutong** [comment]
Attach or detach?

**Comment by yunwei37** [comment]
I think that's both attach or detach.

Maybe we can use a signal to notify the process, the bpftime-agent.so can register a signal handler and do the attach and detach based on the information in the share memory.

**Comment by Officeyutong** [comment]
> I think that's both attach or detach.
> 
> 
> 
> Maybe we can use a signal to notify the process, the bpftime-agent.so can register a signal handler and do the attach and detach based on the information in the share memory.

May be a suitable IPC implementation is better. Signals are too limited

**Comment by yunwei37** [comment]
Is there any other ways can interrupt the running process, give the control flow to the bpf runtime?

We may only use signal for interrupt, the information and attach/detached states should be stored in the shared memory

**Comment by yunwei37** [comment]
I don't think so. The problems is not getting message, since the share memory is already a IPC methods.

The problem is you need to stop the function we want to trace from exec.

**Comment by Officeyutong** [comment]
Sounds good. But note that we may need some flags to avoid the detaching
process being interrupted by another detaching signal. And the signal we
used may not be utilized by the hooked user space program

云微 ***@***.***>于2024年1月25日 周四下午8:29写道：

**Comment by Officeyutong** [comment]
Done by #261
