### ISSUE TITLE
[FEATURE] Need a `bpftime detach PID` command to undo the effects of `bpftime attach`

### ISSUE THREAD

**Issue by agentzh** [eunomia-bpf/bpftime#166]
Currently, there's no way to undo the effects of `bpftime attach`. Hopefully, there's a `bedtime detach PID` command to clean up everything injected into the target process space.

We must be very careful about cleaning up registered "uprobes" though. For example, if the uprobes were set on a dynamically-allocated memory page from the target process's JIT or AOT compilers, then the original breakpoints might already be rewritten or their memory pages might even be freed up.

**Comment by Officeyutong** [comment]
Done by #261
