### ISSUE TITLE
[BUG] bpftime fails to build on Fedora Linux x86_64

### ISSUE THREAD

**Issue by agentzh** [eunomia-bpf/bpftime#170]
I saw a lot of compilation and linking errors when building the latest master branch of bpftime. I've prepared the following patch to address all of them:

https://gist.github.com/agentzh/2d7f763a8a66382c107af6cd3c413823

Sorry that it might contain one unrelated change in Makefile. Please ignore that change in the patch.

I never tested this patch on any other Linux distros, though. So just for your information.

Thanks!
Yichun

**Comment by yunwei37** [comment]
Thanks!

https://github.com/eunomia-bpf/bpftime/pull/161 is adding CI test Officeyut to solve this.

**Comment by yunwei37** [comment]
We have enabled build and test bpftime on Fedora for all CI in #161 and #192, and fix some related errors.

**Comment by Officeyutong** [comment]
> We have enabled build and test bpftime on Fedora for all CI in #161 and #192, and fix some related errors.
> 
> 

But note that we are using Fedora39 for CI. If you encounter errors on other versions, please let me know
