### ISSUE TITLE
[FEATURE] Build options to disable libbpf and Linux kernel interoperability

### ISSUE THREAD

**Issue by agentzh** [eunomia-bpf/bpftime#175]
Currently, the bpftime build always includes libbpf and Linux kernel interoperability, which we don't need in our use cases. It would be nice to have a build option to exclude these things to have much smaller binaries (and also smaller images in the global shm?).

I heard that it might also make it easier to port bpftime to other operating systems like macOS and *BSD (or even Windows?).

**Comment by Bakugo90** [comment]
Hello, 
I would like to work on this issue

**Comment by Officeyutong** [comment]
> Hello, 
> 
> I would like to work on this issue

I've assigned you

**Comment by hp77-creator** [comment]
@yunwei37 @Officeyutong should we try to create bpftime without making `libbpf`? Should I add this option?
