### ISSUE TITLE
[BUG] Support custom LLVM installation locations

### ISSUE THREAD

**Issue by agentzh** [eunomia-bpf/bpftime#187]
My Fedora system's LLVM is too old (10). And I have to compile my own LLVM from source (version 14) and install under `/opt/llvm/`. Currently, the LLVM JIT build of bpftime only looks for system llvm locations, which won't work for my situation:

```
CMake Error at vm/llvm-jit/CMakeLists.txt:46 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Hopefully there is a way to configure the LLVM_DIR without editing any files.

**Comment by Zheaoli** [comment]
Yes, we need to remove the hardcode LLVM path , I'll take handle of this
