### ISSUE TITLE
[BUG] Link in the doc is inaccurate in contributing guideline

### ISSUE THREAD

**Issue by Viveksati5143** [eunomia-bpf/bpftime#224]
**Describe the bug**

The link to create "custom bug report" is inaccurate in the https://github.com/Viveksati5143/bpftime/blob/master/CONTRIBUTING.md#reporting-issues-and-suggesting-new-features

**To Reproduce**

1. Go to 'https://github.com/Viveksati5143/bpftime/blob/master/CONTRIBUTING.md#reporting-issues-and-suggesting-new-features'
2. Click on 'Custom Bug report'

**Expected behavior**

It should lead to [Link](https://github.com/eunomia-bpf/bpftime/issues/new?assignees=&labels=&projects=&template=custom.md&title=) instead of [Link](https://github.com/eunomia-bpf/bpftime/issues/new/choose)

**Screenshots**

![image](https://github.com/eunomia-bpf/bpftime/assets/100852245/3caf46b6-62a7-4018-abbb-07ff3f9b9424)

**Desktop (please complete the following information):**

* OS: [e.g. Windows] Ubuntu
* Version [e.g. 10] 22.04 LTS

**Additional context**

**Comment by yunwei37** [comment]
Thanks! Would you like to open a PR to fix that?
