### ISSUE TITLE
[BUG] runtime should not depend on attach

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#230]
**Describe the bug**

The runtime should be able to be built as a standalone library and doesn't rely on attach targets. However, currently runtime still depends on attach targets:

https://github.com/eunomia-bpf/bpftime/blob/0a3ac616f0c02ee23d8f8ecbfb610cdea19268ba/runtime/CMakeLists.txt#L125-L130

**Expected behavior**

`Runtime` doesn't need `attach` targets as dependencies. It should be `attach` depends on `runtime`.

**Screenshots**

![c7e22e70d2be6c3060b833e7bf6d321](https://github.com/eunomia-bpf/bpftime/assets/34985212/ecb56b6e-41cf-4073-958a-0f824de0ada8)

**Comment by Officeyutong** [comment]
Refactoring of runtime is not done yet, the bpf attach context needs to be rewritten, which was put off

**Comment by Officeyutong** [comment]
And in the current design, the base of all attach impl (base_attach_impl) is in the attach folder. Move it to the runtime folder (If we have cleaned up the runtime folder) so that other attach impls may rely on runtime

**Comment by yunwei37** [comment]
The base_attach_impl should remain in attach dir. We can make it a header only library.
