### ISSUE TITLE
[FEATURE] Simplify the dependence for runtime

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#231]
**Is your feature request related to a problem? Please describe.**

Currently, if I want to use runtime as a library, I need to write a lot of link commands:

```makefile

LDFLAGS =   -L$(ROOTDIR)/build-bpftime/bpftime/runtime  \
			-L$(ROOTDIR)/build-bpftime \
			-L$(ROOTDIR)/build-bpftime/bpftime/vm \
			-L$(ROOTDIR)/build-bpftime/bpftime/third_party/spdlog \
			-L$(ROOTDIR)/build-bpftime/bpftime/FridaGum-prefix/src/FridaGum/ \
			-L$(ROOTDIR)/build-bpftime/bpftime/attach/base_attach_impl \
			-L$(ROOTDIR)/build-bpftime/bpftime/attach/frida_uprobe_attach_impl \
			-L$(ROOTDIR)/build-bpftime/bpftime/attach/syscall_trace_attach_impl \
			-lruntime \
			-lpthread -lm -ldl -lconfig -lnuma -lgcov -lstdc++ -lruntime \
			-lbpftime_base_attach_impl \
			-lbpftime_frida_uprobe_attach_impl \
			-lbpftime_syscall_trace_attach_impl \
			-lvm-bpf -lspdlogd -lbpf \
			-lfrida-gum -lpthread -lm -ldl -lz -lelf 
```

This is not user-friendly and should be simplified.

**Describe the solution you'd like**

It would be better if the `libruntime.a` can be used just like:

```makefile
LDFLAGS =   -L$(ROOTDIR)/build-bpftime/bpftime/runtime  \
			-lruntime
```

**Comment by Officeyutong** [comment]
Please use cmake. Cmake will handle the link stage automatically and you don't need to manually specify all indirect dependencies.

**Comment by Officeyutong** [comment]
It's also impossible to link a single library, since libraries you linked contain both static and dynamic libraries

**Comment by Officeyutong** [comment]
> Please use cmake. Cmake will handle the link stage automatically and you don't need to manually specify all indirect dependencies.

See https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#id25 for details

**Comment by Officeyutong** [comment]
Related to #232 

Building all dependencies into a single static library should solve this issue

**Comment by hp77-creator** [comment]
Hi @Officeyutong #232 only concerns with static libraries, for dynamic libraries we will still need to link them right?

**Comment by Officeyutong** [comment]
> Hi @Officeyutong #232 only concerns with static libraries, for dynamic libraries we will still need to link them right?

Yes

**Comment by yunwei37** [comment]
Fix by https://github.com/eunomia-bpf/bpftime/pull/294
