### ISSUE TITLE
[FEATURE] Add a workflow to run attach tests

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/bpftime#236]
I forget to add a workflow to run attach tests. The following targets are unit tests targets for attach implementation:
- bpftime_frida_uprobe_attach_tests 
- bpftime_syscall_trace_attach_tests 

Add a workflow to run them. Reference: https://github.com/eunomia-bpf/bpftime/blob/master/.github/workflows/test-llvm-jit.yml

**Comment by Sanket-0510** [comment]
hey @Officeyutong can I look into this?

**Comment by Officeyutong** [comment]
> hey @Officeyutong can I look into this?

Sure, I'll assign this issue to you
