### ISSUE TITLE
[BUG] bpftime doesn't compile on ARM architecture, frida test module has errors

### ISSUE THREAD

**Issue by CUIKingdom** [eunomia-bpf/bpftime#237]
**Describe the bug**
The test program under "./bpftime/attach/frida_uprobe_attach_impl/test/"  uses the default x86 configuration and does not take into account the ARM architecture, which prevents it from compiling.

**Screenshots**
ERROR:
![截屏2024-02-27 17 29 09](https://github.com/eunomia-bpf/bpftime/assets/15261143/37f51fc1-b510-4744-a17e-534237337e15)

Source Code:
(1) 
<img width="1090" alt="截屏2024-02-27 17 30 57" src="https://github.com/eunomia-bpf/bpftime/assets/15261143/b6c05607-502e-41fe-9dec-ddc099b50ced">

(2) 
<img width="1194" alt="截屏2024-02-27 17 31 53" src="https://github.com/eunomia-bpf/bpftime/assets/15261143/f730fa77-cafa-4741-94f5-a9ed0a506686">

(3) 
<img width="858" alt="截屏2024-02-27 17 32 28" src="https://github.com/eunomia-bpf/bpftime/assets/15261143/08a420f3-d54d-4d12-bc0c-a0b0649cd485">

**Desktop (please complete the following information):**

* OS: Ubuntu 23.10
* Version: bpftime 0.0.3

**Additional context**

**Comment by Officeyutong** [comment]
These tests only support x86. Contribution for other platforms are welcomed

**Comment by yunwei37** [comment]
Can we disable these tests on arm build?

**Comment by yunwei37** [comment]
We should have a cmake flag to do that.
