### ISSUE TITLE
[FEATURE] Add an example to show how to write a dyamically loaded attach implementation

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/bpftime#246]
After https://github.com/eunomia-bpf/bpftime/issues/235 was done, we should be able to support dynamically loaded attach impl. Write an example to tell user how to do this.

**Comment by yunwei37** [comment]
Can we make it a good first issue? If you think it's possible, you can add more description about the API, the unit test and where should people place the example.

**Comment by Officeyutong** [comment]
> Can we make it a good first issue? If you think it's possible, you can add more description about the API, the unit test and where should people place the example.

OK, I will take it
