### ISSUE TITLE
[FEATURE] Add cmake options to control build runtime interact with kernel maps

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#251]
**Is your feature request related to a problem? Please describe.**

See #145 and #175

**Describe the solution you'd like**

Add a cmake option BPFTIME_BUILD_KERNEL_BPF, which can control whether to build the shared maps between kernel and userspace. Disable these options will not build the source code in 
https://github.com/eunomia-bpf/bpftime/tree/master/runtime/src/bpf_map/shared

**Comment by Officeyutong** [comment]
Note that program map also requires libbpf

**Comment by hp77-creator** [comment]
@Officeyutong does that mean we can't disable libbpf?

**Comment by Officeyutong** [comment]
> @Officeyutong does that mean we can't disable libbpf?

We may disable features that rely on libbpf

**Comment by hp77-creator** [comment]
Hi @Officeyutong @yunwei37 Can you assign me this issue, I will send a PR asap.
