### ISSUE TITLE
[FEATURE] Make LLVM JIT as default JIT

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#262]
**Is your feature request related to a problem? Please describe.**

The LLVM JIT has better performance and more stable now. It would be better to make it default.

**Describe the solution you'd like**

1. Update the Makefile and CMake to make LLVM JIT compiled by default
2. Update the documents in https://github.com/eunomia-bpf/eunomia.dev, make sure it includes how to install llvm-dev and compile bpftime with llvm-jit. The quick start and install page may also need updated.
3. Check the release and docker image, make sure it works

**Comment by NobinPegasus** [comment]
I will be able to solve 1 & 2. Not sure about the third one.
@yunwei37
