### ISSUE TITLE
[BUG]  After installing the development environment, the version number cannot be queried through the command

### ISSUE THREAD

**Issue by yuanrui77** [eunomia-bpf/bpftime#272]
Operating system: ubuntu22.04

In docker environment:
Enter the command: bpftime -v
Show version: 1.0

Without using the docker environment, follow the steps yourself and run through the provided cases.
Enter the command: bpftime -v
No version number shown

**Comment by NobinPegasus** [comment]
It's working fine on my local machine. Have you built the tool successfully on your local machine?
Have you used these commands?
```
make release JOBS=$(nproc) # Build and install the runtime
export PATH=$PATH:~/.bpftime
```

```
pegasus@pegasus:~/Documents/bpftime$ bpftime -v
1.0
```

**Comment by yuanrui77** [comment]
Yes, the reason was that I didn't have a successful build, now the problem has been solved, thank you
