### ISSUE TITLE
Running hot-patch examples

### ISSUE THREAD

**Issue by aFuerst** [eunomia-bpf/bpftime#365]
Hello, I'm having trouble understanding and running the [hot patch examples](https://github.com/eunomia-bpf/bpftime/tree/master/example/patch/redis). 

They make use of a cli which doesn't seem to exist any more (`bpftime-cli`), which I think is just now [`bpftime`](https://github.com/eunomia-bpf/bpftime/blob/master/tools/cli/CMakeLists.txt#L6). However that definitely does not have the same functionality as expected in the examples [like here](https://github.com/eunomia-bpf/bpftime/blob/master/example/patch/redis/README.md?plain=1#L69). 

Both examples prepare a patch (this is unexplained), and take a generated JSON file (no examples exist I can find, and unexplained how it's made) and give it to the CLI to patch something.

What is the correct way to get the hot-patching to work?

**Comment by Officeyutong** [comment]
The README is too old, for now you may use `bpftime load redis-patch` and `bpftime attach <pid to redis server>` instead
