### ISSUE TITLE
[BUG] ci does not use project libbpf

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#48]
**Describe the bug**

![0766a16ff1b686470f7ecf9bdaa468b](https://github.com/eunomia-bpf/bpftime/assets/34985212/6bd08017-070f-45a0-8c79-4fcbf0595ec1)

**To Reproduce**

make unit-test

it seems that the program is using local headers

**Comment by Officeyutong** [comment]
Unable to reproduce. CI `test-runtime.yml` does not install libbpf system wide, but it runs successfully. I also examined and analyzed my code, in the current implementation, the build of `ebpf_program_target` will use `LIBBPF_INCLUDE_DIRS`, while the generation of the folder was controlled by target copy_headers, which is a dependency of all ebpf_program_targets.

**Comment by yunwei37** [comment]
OK. Just leave it here.

**Comment by yunwei37** [comment]
https://github.com/eunomia-bpf/bpftime/pull/52

modify a line will make local compile pass but ci failed.

**Comment by Officeyutong** [comment]
I'll take a look into it in recent days
