### ISSUE TITLE
[FEATURE] Remove and replace simple-jit with ubpf jit 

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#90]
**Is your feature request related to a problem? Please describe.**

We don't want to maintain different jit. The https://github.com/eunomia-bpf/bpftime/tree/master/vm/simple-jit was original ported from ubpf, there is no need to maintain it further.

We can use JIT directly from ubpf for resource constraints device where LLVM JIT is not suitable.

**Comment by yunwei37** [comment]
The simple jit has a lot of bugs. I think it would be better to make it updated.

**Comment by Officeyutong** [comment]
Do we need to add ubpf as a dependency or port the JIT of ubpf to our project?
