### ISSUE TITLE
[FEATURE] Enhance documents

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#92]
**Is your feature request related to a problem? Please describe.**

We need more documents:

- [ ] Description of how to use bpftime for uprobe, syscall tracing
- [ ] The details of how bpftime works

**Describe the solution you'd like**

Add documents in eunomia.dev

**Describe alternatives you've considered**

**Provide usage examples**

**Additional context**

**Comment by Viveksati5143** [comment]
Hey @yunwei37,
I would like to contribute to this issue as my first contribution in your org.
So, can you please assign it to me to get the work done?
Thanks.

**Comment by yunwei37** [comment]
Thanks!

**Comment by yunwei37** [comment]
The documents have been moved to https://github.com/eunomia-bpf/eunomia.dev/blob/main/docs/bpftime

So please update the documents there

**Comment by yunwei37** [comment]
Maybe you can first update the documents for bpftimetool?

https://github.com/eunomia-bpf/bpftime/tree/master/tools/bpftimetool

**Comment by Viveksati5143** [comment]
Sure, looking into it,..

**Comment by Viveksati5143** [comment]
> Maybe you can first update the documents for bpftimetool?
> 
> https://github.com/eunomia-bpf/bpftime/tree/master/tools/bpftimetool
> 
> You can create a new markdown file in the eunomia.dev repo, and updated the https://github.com/eunomia-bpf/eunomia.dev/blob/main/mkdocs.yaml for that.
> 
> The website will be updated automatically once the PR is merged.

Can you provide what in the documentation should be updated?

**Comment by yunwei37** [comment]
You can create a new markdown file like https://github.com/eunomia-bpf/eunomia.dev/blob/main/docs/bpftime/documents/co-re.md in https://github.com/eunomia-bpf/eunomia.dev/blob/main/docs/bpftime/documents/, add details about bpftimetool, and update the https://github.com/eunomia-bpf/eunomia.dev/blob/main/mkdocs.yaml for the new doc.
