### ISSUE TITLE
[FEATURE] Add more examples from libbpf-tools

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#94]
**Is your feature request related to a problem? Please describe.**

Please help us port and test more examples from https://github.com/iovisor/bcc/tree/master/libbpf-tools

**Describe the solution you'd like**

Put examples in https://github.com/eunomia-bpf/bpftime/tree/master/example/libbpf-tools.

**Comment by Officeyutong** [comment]
Seems that all supported programs from libbpf-tools were added to here

**Comment by yunwei37** [comment]
Thanks to you all!
