### ISSUE TITLE
[BUG] bpftrace doesn't terminating correctly

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpftime#99]
**Describe the bug**

bpftrace doesn't terminating correctly, it does't response with Ctrl C.

reproduce:

1. Install bpftrace with package manager: `apt install bpftrace`
2. Run bpftrace

```sh
sudo SPDLOG_LEVEL=error ~/.bpftime/bpftime load bpftrace -- -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
```

**Expected behavior**

Ctrl C will perform correctly.

**Comment by Officeyutong** [comment]
Please use the bpftrace from the repo of iovisor
